apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          securityContext:
            runAsGroup: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        app: notification-controller
    spec:
      containers:
        - name: manager
          securityContext:
            runAsGroup: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        app: source-controller
    spec:
      containers:
        - name: manager
          securityContext:
            runAsGroup: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      containers:
        - name: manager
          securityContext:
            runAsGroup: 1000
